name: CI-pullrequest

on:
  pull_request:
    branches:
      - dev-v2.6

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Checkout into branch
        run: git checkout -b staging-pr-workflow

      - name: Pull scripts
        run: sudo make pull-scripts

      - name: Pull in all relevant branches
        run: git fetch origin release-v2.6
      
      - name: Validate 
        run: sudo make validate
